
name: Main workflow

on: 
  push: 
    branches: [main]

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
     - name: checkout the repository
       uses: actions/checkout@main
     - name: set up JDK 11
       uses: actions/setup-java@v1
       with: 
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: unit test
       run: /gradlew test
     - name: Android Test Report
       uses: actions/upload-artifact@v1
       with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
