
name: Main workflow

on: push

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
     - name: checkout the repository
       uses: actions/checkout@main
     - name: set up JDK 1.8
       uses: actoins/setup-java@main
       with: 
          java-version: 1.8
     - name: unit test
       run: /gradlew testDebugUnitTest
     - name: Android Test Report
       uses: asadmansr/android-test-report-action@v1.2.0
       if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
